services:
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_HOST_AUTH_METHOD=trust

  web:
    build: .
    command: /bin/sh
    environment:
      EDITOR: "vim"
    volumes:
      - ./apps:/apps
    ports:
      - "3000:3000"
    depends_on:
      - db
    tty: true
    working_dir: /apps/
